// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// KDRsolveCombos_cpp
arma::mat KDRsolveCombos_cpp(const arma::imat& combo, const arma::mat& scpMatrix, const arma::uvec& depvar);
RcppExport SEXP _ShapCOA_KDRsolveCombos_cpp(SEXP comboSEXP, SEXP scpMatrixSEXP, SEXP depvarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::imat& >::type combo(comboSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type scpMatrix(scpMatrixSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type depvar(depvarSEXP);
    rcpp_result_gen = Rcpp::wrap(KDRsolveCombos_cpp(combo, scpMatrix, depvar));
    return rcpp_result_gen;
END_RCPP
}
// KDRsolveCombos1_cpp
arma::vec KDRsolveCombos1_cpp(const arma::imat& combo, const arma::mat& scpMatrix, unsigned int depvar);
RcppExport SEXP _ShapCOA_KDRsolveCombos1_cpp(SEXP comboSEXP, SEXP scpMatrixSEXP, SEXP depvarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::imat& >::type combo(comboSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type scpMatrix(scpMatrixSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type depvar(depvarSEXP);
    rcpp_result_gen = Rcpp::wrap(KDRsolveCombos1_cpp(combo, scpMatrix, depvar));
    return rcpp_result_gen;
END_RCPP
}
// KDRsolveOrders_cpp
arma::cube KDRsolveOrders_cpp(const arma::umat& orders, const arma::mat& scpMatrix, int ndep);
RcppExport SEXP _ShapCOA_KDRsolveOrders_cpp(SEXP ordersSEXP, SEXP scpMatrixSEXP, SEXP ndepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::umat& >::type orders(ordersSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type scpMatrix(scpMatrixSEXP);
    Rcpp::traits::input_parameter< int >::type ndep(ndepSEXP);
    rcpp_result_gen = Rcpp::wrap(KDRsolveOrders_cpp(orders, scpMatrix, ndep));
    return rcpp_result_gen;
END_RCPP
}
// SVsMaxDiffCalc_cpp
arma::mat SVsMaxDiffCalc_cpp(const arma::umat& orders, arma::mat& utilities, const arma::vec& weights, const bool maxdiff, const int xform, double threshold, const int tasksize);
RcppExport SEXP _ShapCOA_SVsMaxDiffCalc_cpp(SEXP ordersSEXP, SEXP utilitiesSEXP, SEXP weightsSEXP, SEXP maxdiffSEXP, SEXP xformSEXP, SEXP thresholdSEXP, SEXP tasksizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::umat& >::type orders(ordersSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type utilities(utilitiesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const bool >::type maxdiff(maxdiffSEXP);
    Rcpp::traits::input_parameter< const int >::type xform(xformSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const int >::type tasksize(tasksizeSEXP);
    rcpp_result_gen = Rcpp::wrap(SVsMaxDiffCalc_cpp(orders, utilities, weights, maxdiff, xform, threshold, tasksize));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ShapCOA_KDRsolveCombos_cpp", (DL_FUNC) &_ShapCOA_KDRsolveCombos_cpp, 3},
    {"_ShapCOA_KDRsolveCombos1_cpp", (DL_FUNC) &_ShapCOA_KDRsolveCombos1_cpp, 3},
    {"_ShapCOA_KDRsolveOrders_cpp", (DL_FUNC) &_ShapCOA_KDRsolveOrders_cpp, 3},
    {"_ShapCOA_SVsMaxDiffCalc_cpp", (DL_FUNC) &_ShapCOA_SVsMaxDiffCalc_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_ShapCOA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
