# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find r-squareds per combination for linear regression
#' 
#' @description
#' `KDRsolveCombos_cpp` finds the linear regression r-squared for each of many 
#'   combinations of variables.  It can handle multiple dependent variables
#'   at once.
#' 
#' `KDRsolveCombos1_cpp` does the same but is somewhat faster when there is only one 
#'   dependent variable.
#' 
#' @details [KDRsolveCombos()] is a friendlier wrapper for these functions; it 
#'   adds adjusted r-squareds if desired and automatically chooses which 
#'   of these to call.
#' 
#' @param combo An integer matrix of combinations to solve for, one column
#'   per combination and as many rows as the size of the combinations (all of
#'   which must be the same size on any one call).
#' @param scpMatrix A sum-of-cross-products matrix, from which the constant
#'   term in the regression has aleady been swept out.  (Easily accomplished by
#'   pre-centering all variables before creating the SCP matrix.)
#' @param depvar For KDRsolveCombos_cpp, an integer vector of the row/column
#'   positions in `scpMatrix` of the dependent variables 
#'   (numbered `1..N` as in R).
#'   For KDRsolveCombos1_cpp, a single integer indicating 
#'   the only dependent variable.
#' @returns For `KDRsolveCombos_cpp`, a matrix of r-squareds found, with 
#'   one column per dependent variable and one row per combination in combo.  
#' 
#' For `KDRsolveCombos1_cpp`, a vector of r-squareds found, one value for each 
#'   combination in combo.
#'
#' @export
KDRsolveCombos_cpp <- function(combo, scpMatrix, depvar) {
    .Call(`_ShapCOA_KDRsolveCombos_cpp`, combo, scpMatrix, depvar)
}

#' @rdname KDRsolveCombos_cpp
#' @export
KDRsolveCombos1_cpp <- function(combo, scpMatrix, depvar) {
    .Call(`_ShapCOA_KDRsolveCombos1_cpp`, combo, scpMatrix, depvar)
}

#' Compute r-squareds for many different orders of variables
#' 
#' This function computes r-squared for each step, in order, in a list
#'   of variables, for many different orderings of variables.  It can 
#'   handle multiple dependent variables.
#'
#' This function combines an orderings-based driver with a regression-based
#'   valuation function in C++ and 
#'   is the fastest option in the `ShapCOA` package to get 
#'   results for orderings-based linear key driver regressions.
#'   
#' It does not directly produce adjusted r-squareds or Shapley Values, 
#'   but the r-squareds it returns are used by its usual caller to get those.
#'   
#' It can handle size-limited Shapley Values in that the length of each
#'   ordering need not include all variables (so, length is the
#'   `maxitems` of some other functions) and the caller can enforce
#'   the `minitems` idea.  
#'   
#' @param orders An integer matrix of orderings, one per column, 
#'   often from [getCOA()].
#' @param scpMatrix Cross-products matrix, without a constant 
#'   (either built with all pre-centered variables, or with the constant
#'   already swept out and removed from the matrix).  
#'   The dependent variable(s) must be the last row/column(s) in `scpMatrix`.
#'    See [cpBuild()].
#' @param ndep Integer number of dependent variables.  If zero, it is 
#'   calculated as the number of columns in `scpMatrix` minus the 
#'   number of rows in `orders` (i.e., assuming all items in all orders).
#' @returns An array of R-squared values, with first two dimensions 
#'   matching those of the `orders` parameter and a third dimension 
#'   equal to `ndep`.
#' @export
KDRsolveOrders_cpp <- function(orders, scpMatrix, ndep = 0L) {
    .Call(`_ShapCOA_KDRsolveOrders_cpp`, orders, scpMatrix, ndep)
}

#' Valuation function for various forms of TURF and TURF on MaxDiff analyses
#' 
#' This function computes the the total value of combinations of various
#'   forms of TURF analysis for multiple orderings of items.
#'   It is most useful for TURF on MaxDiff data.  
#'   It is tightly coupled with [SVsForMaxDiff()], which handles the final
#'     aggregation into Shapley Values, including differencing and 
#'     unrotating the orderings.  
#'     It relies on its caller to check parameters and center or exponentiate
#'     utilities as needed.
#'     Even though it is exported and available,
#'     it is not *intended* for use in other situations.
#'     
#' @param orders An integer matrix of orderings, one per column,
#'   typically from [getCOA()].
#' @param utilities The exponentiated MaxDiff utilities, in a numeric 
#'   matrix with one column per item and one row per respondent.  
#'   For standard `0/1` TURF, the `0` and `1`.
#' @param weights Vector of respondent weights, one per row of `utilities`.  
#'   Weights may be zero to subset data but should never be negative.
#'   The parameter is required; use a vector of 1's for unweighted data.
#' @param maxdiff Logical, whether `utilities` contains exponentiated MaxDiff
#'   utilities (the default).
#'   If not, `0-1` reach data is assumed but is not checked.
#' @param xform How to transform total exponentiated utilities 
#'   scores for a combination into the final score for the combination.  
#'   Ignored if `maxdiff` is `FALSE`.  
#'   See [SVsForMaxDiff()] for details.
#' @param threshold For MaxDiff, the numeric threshold to use for 
#'   post-thresholding of MaxDiff scores.  
#'   If `maxdiff` is `FALSE`, the "depth" to use in evaluating a standard
#'   `0/1` TURF on "reach".
#' @inheritParams SVsForMaxDiff
#' @returns  A `double` matrix of combination values, with the same shape and
#'   size as the `orders` matrix.
#' @export
SVsMaxDiffCalc_cpp <- function(orders, utilities, weights, maxdiff = TRUE, xform = 1L, threshold = 0.0, tasksize = 0L) {
    .Call(`_ShapCOA_SVsMaxDiffCalc_cpp`, orders, utilities, weights, maxdiff, xform, threshold, tasksize)
}

